import 'package:firebase_core/firebase_core.dart';
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgRlrpafq0N9uGBTCXoPKLHZN_F3yqL-8',
    appId: '1:212873494173:web:d75aef49c713175d20de74',
    messagingSenderId: '212873494173',
    projectId: 'sensory-safari',
    authDomain: 'sensory-safari.firebaseapp.com',
    storageBucket: 'sensory-safari.firebasestorage.app',
    measurementId: 'G-K7MD22YTJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA7KHgaj6p5oD4D0fZFVARIqK3wPzs2CQ',
    appId: '1:212873494173:android:d958c2c8584a50f120de74',
    messagingSenderId: '212873494173',
    projectId: 'sensory-safari',
    storageBucket: 'sensory-safari.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLpLJOfpX-AVdh73Tv9Ade0fPqNMszRnw',
    appId: '1:212873494173:ios:7e680aa48d9477e420de74',
    messagingSenderId: '212873494173',
    projectId: 'sensory-safari',
    storageBucket: 'sensory-safari.firebasestorage.app',
    iosBundleId: 'com.example.sensorySafariFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLpLJOfpX-AVdh73Tv9Ade0fPqNMszRnw',
    appId: '1:212873494173:ios:7e680aa48d9477e420de74',
    messagingSenderId: '212873494173',
    projectId: 'sensory-safari',
    storageBucket: 'sensory-safari.firebasestorage.app',
    iosBundleId: 'com.example.sensorySafariFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgRlrpafq0N9uGBTCXoPKLHZN_F3yqL-8',
    appId: '1:212873494173:web:4ffb3f73da23211320de74',
    messagingSenderId: '212873494173',
    projectId: 'sensory-safari',
    authDomain: 'sensory-safari.firebaseapp.com',
    storageBucket: 'sensory-safari.firebasestorage.app',
    measurementId: 'G-5ZC4FG32CD',
  );
}
